spring.application.name=encuentra-me
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE

#springdoc.api-docs.path=/encuentra-me-api-docs
#springdoc.swagger-ui.path=/encuentra-me-api-docs-ui.html

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# JWT Configuration
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# Server Configuration
server.port=8080
server.error.include-message=always

# AWS RDS Database Configuration
spring.datasource.url=jdbc:postgresql://encuentrame-db.c7ko2ww4w9ha.us-east-2.rds.amazonaws.com:5432/encuentrame
spring.datasource.username=encuentrameadmin
spring.datasource.password=EncuentraMeDB

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.root=DEBUG

#AWS keys configuration - solicitar keys
aws.accessKey="solicitar"
aws.secretKey="solicitar"
aws.region=us-east-1