spring.application.name=encuentra-me
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#options: update | create-drop
spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE

#springdoc.api-docs.path=/encuentra-me-api-docs
#springdoc.swagger-ui.path=/encuentra-me-api-docs-ui.html

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# JWT Configuration
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# Server Configuration
server.port=8080
server.error.include-message=always

# AWS RDS Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.show-sql=true

logging.level.root=DEBUG

#AWS keys configuration
aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}
aws.region=us-east-1